name: influxdb
vendor: Chen-Han Hsiao (Stanley) <stanley.hsiao@canonical.com>
architectures: [amd64, armhf]
icon: meta/influxdb.jpg
version: 0.9.4.2-2
services:
  - name: webserver
    description: "Influxdb"
    start: start-service.sh
    ports:
      external:
        ui:
          port: 8083/tcp
          negotiable: no
    security-override:
      seccomp: meta/influxdb.filter
      apparmor: meta/influxdb.apparmor 
